version: "3"

services:
  git-server:
    image: git-server-image
    ports:
      - 8083:80
    volumes:
      - ./repos:/repos
      - ./nginx.conf:/etc/nginx/nginx.conf
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      REPO_USER: ${REPO_USER}
      REPO_PASSWORD: ${REPO_PASSWORD}
